services:
    faker.provider.issue:
        class: AppBundle\DataFixtures\Faker\Provider\IssueProvider
        tags: [ { name: hautelook_alice.faker.provider } ]
    faker.provider.comment:
        class: AppBundle\DataFixtures\Faker\Provider\CommentProvider
        tags: [ { name: hautelook_alice.faker.provider } ]