AppBundle\Entity\User:
  user:
    username: user
    plainpassword: user
    email: user@example.com
    enabled: true
  admin:
    username: admin
    plainpassword: admin
    email: admin@example.com
    enabled: true
    roles: [ROLE_ADMIN]
  staffer1:
      username: 'john.doe'
      email: '<email()>'
      enabled: true
      plainpassword: staffer
      roles: [ROLE_STAFFER]
  staffer2:
      username: 'jane.smith'
      email: '<email()>'
      enabled: true
      plainpassword: staffer
      roles: [ROLE_STAFFER]
  customer{1..10}:
      username: '<username()>'
      email: '<email()>'
      enabled: true
      plainpassword: user

AppBundle\Entity\Issue:
    issue{1..40}:
        subject: Issue_#<current()>
        description: <paragraphs(3, true)>
        status: <status()>
        createdAt: <dateTimeBetween('-3 months')>
        updatedAt: '<dateTimeBetween($createdAt, "now")>'
        creator: '@customer*'
        editor: '@self->creator'
        staffer: '@staffer*'
    issue{41..60}:
        subject: Issue_#<current()>
        description: <paragraphs(3, true)>
        status: open
        createdAt: <dateTimeBetween('-3 months')>
        updatedAt: '<dateTimeBetween($createdAt, "now")>'
        creator: '@customer*'
        editor: '@self->creator'

AppBundle\Entity\Comment:
    comment{1..60}:
        issue: '@issue*'
        createdAt: <dateTimeBetween('-1 week')>
        updatedAt: '@self->createdAt'
        body: <body(3,true)>
        creator: '@customer*'
        editor: '@self->creator'